### ISSUE TITLE
Compilation error in VS2015

### ISSUE THREAD

**Issue by threebrooks** [kkm000/openfst#1]
I'm getting a:

`src/include/fst/string-weight.h(176): error C2039: 'const_reverse_iterator': is not a member of 'std::remove_reference<std::list<int,std::allocator<_Ty>>>'`

and I see that this is one of the changes made for the Windows port. When I revert it to the original line

line 176: `typename std::list<Label>::const_iterator iter_;`

it compiles. Have you seen this before?

**Comment by kkm000** [comment]
That's nasty. I am using VS2015 for my own main OpenFST project, and not getting the error. What toolset are you using? Have you updated Visual Studio to the latest update version (Help/About)?

The problem is there is a bug in the Microsoft compiler, both in VS 2015 and 2017; look how the same line has changed in the original OpenFST (the orig/1.6 branch here). I added the `std::remove_reference` although it is not required, only to work around the bug, and this workaround is what giving you the trouble.

**Comment by kkm000** [comment]
For comparison: my Help/About box shows "Version 14.0.25431.01 Update 3", the toolset as selected in the project is "Visual Studio 2015 (v140)", and cl version is 19.00.24215.1. I just checked out fresh project and compiled it. Please check what are yours.

**Comment by bahtity** [comment]
I faced also the same problem.
Although here what I did just to make the compiler happy, although I am not sure if the code will hit at run time or even either it will work as intended.
in the file string-weight.h, you need to modify line 176 from 
`typename std::remove_reference<decltype (Weight::rest_)>::const_reverse_iterator iter_;`
to 
`typename std::remove_reference<decltype (Weight::rest_)>::type::const_reverse_iterator iter_;`

than in top of class StringWeightIterator , line 140, add the following code,  this actually implement the comparison operator the compiler is looking for.
```
static bool operator == (const std::reverse_iterator<std::_List_const_iterator<std::_List_val<std::_List_simple_types<int>>>> & a, std::_List_const_iterator<std::_List_val<std::_List_simple_types<int>>> &b) 
{
	return a.operator*() == b.operator*();
}
```
I have visual studio  2015 build 14.0.25431.01  update 3

**Comment by kkm000** [comment]
Fixed, thanks. The issue only occurs when using the template, not when compiling the library itself!

@bahtity, I applied your suggested fix with the missing `::type`, thank you, but the second part escapes me. It does not seem right. Note the left of the comparison if an iterator specialized on an iterator, like it's a reverse_iterator on a container of iterators, not values! I suspect a missing iterator dereference somewhere in the code that calls the library. If you have a piece of code that reproduces this error, please open a new issue!

**Comment by bahtity** [comment]
@kkm000 , you may be right. actually I tried to find the code call this operator but I could not.
I can see your point by trying simplifying the operator code to be like this : 
```
typedef std::_List_simple_types<int> STD_SLT;
typedef std::_List_val<STD_SLT> STD_SLT_V;
typedef std::_List_const_iterator<STD_SLT_V > STD_LCI_SLT_V;
static bool operator == (const	std::reverse_iterator		<STD_LCI_SLT_V> & a, STD_LCI_SLT_V &b)
{
return a.operator*() == b.operator*();
}
```
if we assumed that the function of the comparison operator is to compares the value the iterator points  to the right implantation would be `return *a == *b ;` instead of `return a.operator*() == b.operator*();`
i tried the final code and it compile correctly. 
```
typedef std::_List_simple_types<int> STD_SLT;
typedef std::_List_val<STD_SLT> STD_SLT_V;
typedef std::_List_const_iterator<STD_SLT_V > STD_LCI_SLT_V;
static bool operator == (const	std::reverse_iterator		<STD_LCI_SLT_V> & a, STD_LCI_SLT_V &b)
{
	return *a == *b;
}
```

**Comment by kkm000** [comment]
@bahity: Good, thanks for confirming!
