### ISSUE TITLE
Access denied: Unable to start the program .../ALL_BUILD

### ISSUE THREAD

**Issue by shaonmostafiz** [kkm000/openfst#37]
While building the openfst.sln using VS15 2017 on windows 10, it is saying access denied: Unable to start the program .../ALL_BUILD. I guess its an configuration error. Can anyone please help me out?  

![image](https://user-images.githubusercontent.com/4390553/109254279-ecf71d00-781b-11eb-8750-15b6aa24c47a.png)

**Comment by kkm000** [comment]
This is by design. A single .vcxproj file is invoked multiple times to build each of the binaries. If you want to debug an FST binary, specify its path in the Debug properties. You will need to provide some arguments in the same dialog box anyway (all FST binaries require arguments), so I do not see this as an issue.
