### ISSUE TITLE
Can't run on windows-xp

### ISSUE THREAD

**Issue by jiejiehao** [kkm000/openfst#38]
hi I have a problem，Compile openfst with the vs toolset v140_xp, but Can't run on windows-xp, when the program starts, it will not report an error, but it will get stuck.

**Comment by kkm000** [comment]
Windows XP has been EOL for more than 7 years. We cannot support it, and if we could, we wouldn't for ethical reasons, sorry—it would imply condoning user's self-harm by continuing to run the extremely obsolete and therefore insecure OS.

Also, the toolset 14.0 is too old. Toolsets 14.1 and 14.2 are fine.

For your safety, you should **never run Windows XP**. Since its end of support in April 2014, only _one_ security patch has been issued 4 years ago, in 2017, as a one-time exception, for the famous WannaCry virus. That patch might be installed only manually by downloading and running an installer, as Windows Update for Windows XP has been long shut down by then. This OS has a large number of well-known security exploits discovered since its end of support. Your machine _will_ be pwnd, and likely has already been. Please upgrade.
